### ISSUE TITLE
SNS notifications do not include input details for some or all job inputs

### ISSUE THREAD

**Issue by jilladams** [aws-solutions/video-on-demand-on-aws-foundation#11]
VOD Foundations relies on MediaConvert's INPUT_INFORMATION cloudwatch event to return details for all the inputs used in a job. However, In MediaConvert, INPUT_INFORMATION is not guaranteed to return before COMPLETED events from cloudwatch for quick jobs. This means that in some cases the job may complete and SNS notification be sent without including job input information.

https://app.asana.com/0/1200382082298559/1200470174838695/f

**Comment by Thomas-Minnebo** [comment]
I'm using the default AWS VOD template (no modifications) and also have this problem.

`"StatusUpdateInterval": "SECONDS_60"`

Doesn't help. Any updates on this?

**Comment by atrancandoris** [comment]
@Thomas-Minnebo I just encountered this issue. I added a wait to `jobComplete/lib/utils.js` at the top of the `try` for `writeManifest`:

```
const timeout = (ms) => new Promise(resolve => setTimeout(resolve, ms));

if (!jobDetails.detail) {
    await timeout(10000);
    console.log(`Waiting 10 seconds for InputDetails...`);
}
```

This will greatly increase the probability that the manifest `inputDetails` are written before the complete job event retrieves the manifest from `s3`.
