### ISSUE TITLE
Build tools or additional docs on how to validate MediaConvert job templates. 

### ISSUE THREAD

**Issue by eggoynes** [aws-solutions/video-on-demand-on-aws-foundation#21]
**Is your feature request related to a problem? Please describe.**
Have a more detailed explanation on how to use new job template files. See if there is a way to validate Job templates before use.

**Comment by darylteo** [comment]
You can import Job Templates using the MediaConvert Management Console 

https://ap-southeast-2.console.aws.amazon.com/mediaconvert/home?region=ap-southeast-2#/templates/list

Just "import template" and if anything is wrong with the template it'll tell you.
