### ISSUE TITLE
I don't have access to the cloudfront url

### ISSUE THREAD

**Issue by cdeavila** [aws-solutions/video-on-demand-on-aws-foundation#22]
I have completely and without error implemented the cloudformation template from the guide indicated at: https://aws.amazon.com/es/solutions/implementations/video-on-demand-on-aws/, everything is correct, but at When I need to access the video with the cloudfront URL generated by the template, I get an access denied notice, so I consume the videos already transcoded in the S3 bucket, because I don't have access to the cloudfront distribution URL, Please if someone could help me. Leave any screnshots for a better understanding.
<img width="986" alt="image" src="https://user-images.githubusercontent.com/90292019/189224998-de858e91-f967-4aeb-8cef-f7dfc47810b2.png">
<img width="956" alt="image" src="https://user-images.githubusercontent.com/90292019/189225100-c952c98d-eac7-4e5c-a2c6-0b63a592db25.png">
<img width="831" alt="image" src="https://user-images.githubusercontent.com/90292019/189225191-4cbf718a-9fcb-48d6-bd13-bed705cfa3fe.png">

**Comment by sandimciin** [comment]
Hi cdeavila, thanks for providing screenshots. We were able to reproduce the problem and added the issue to our backlog.

**Comment by SamDesmondKing** [comment]
Hi there! Any update on this? I'd love to use this solution but can still reproduce this. 

Follow-up question, any plans to update node from 12.x, given that it's deprecated in lambda a month from now?

**Comment by sandimciin** [comment]
Yes, the next release of this solution will be updated to node 16.

Can you try accessing the cloudfront hls endpoint generated in the notification email?
<img width="758" alt="Screenshot 2023-04-24 at 2 03 02 PM" src="https://user-images.githubusercontent.com/17505538/234116627-d71935d3-c76e-48a5-b2e2-208138d2f1e0.png">

**Comment by SamDesmondKing** [comment]
Thanks for the update! Yes I was able to access the url without issues, my mistake.
