### ISSUE TITLE
Error validate the Job.setting.json

### ISSUE THREAD

**Issue by cdeavila** [aws-solutions/video-on-demand-on-aws-foundation#23]
I have problems when uploading the video in the Input Bucket, I receive a notification in my email indicating that the download of the file failed, I leave the specific message:

  "Mistake": {
     "Message": "Failed to download and validate the job-settings.json file. Please check its contents and location. Details on using custom settings: https://nam10.safelinks.protection.outlook.com/?url=https% 3D%7C3000%7C%7C%7C&amp;sdata=QFshicn4hdr3fy9JCYHt5GjrxDzkM7mfInJ7KrcbZfY%3D&amp;reserved=0",
     "Error": "AccessDenied: Access Denied"

**Comment by cassneal** [comment]
Thank you for opening this issue. We have added this to our backlog to look into.

**Comment by affanshahab** [comment]
seeing same issue

**Comment by cassneal** [comment]
I have escalated this to get it prioritized in the backlog. Thanks.

**Comment by benhindle** [comment]
Same issue here

**Comment by benhindle** [comment]
Don't forget to add your uploaded file to <bucketName>/assets01. Solved the error for me.

**Comment by cassneal** [comment]
Hi @cdeavila we are looking into this. can you clarify for us.. "I have problems when uploading the video in the Input Bucket", are you uploading into the root of the bucket?

**Comment by sandimciin** [comment]
hi @cdeavila please refer to this section of the Implementation Guide for reference: https://docs.aws.amazon.com/solutions/latest/video-on-demand-on-aws-foundations/components.html

For the next release, we will update the Implementation Guide so that it is more specific.
