### ISSUE TITLE
Is there sample for this foundation in python

### ISSUE THREAD

**Issue by PankajSavaliya** [aws-solutions/video-on-demand-on-aws-foundation#25]
Hi,

I'm looking for the same foundation in python.

**Comment by eggoynes** [comment]
Hi @PankajSavaliya 

Thank you for the message. 

Currently we just have this Github project in JavaScript. The job-submit and job-complete could be converted to Python. 

We have examples here of how to use the SDK for Python. 
https://docs.aws.amazon.com/mediaconvert/latest/apireference/python.html

I also found this old python project that can convert files in MediaConvert, that could be useful too. 
https://github.com/aws-samples/aws-media-services-vod-automation/blob/master/MediaConvert-WorkflowWatchFolderAndNotification/convert.py
