### ISSUE TITLE
Support for Israel(Tel Aviv) Region "il-central-1"

### ISSUE THREAD

**Issue by veltz-avi** [aws-solutions/video-on-demand-on-aws-foundation#36]
The solution deployment is failing in Israel(Tel Aviv) Region "il-central-1"
Version: 1.3.2
Released: 11/2023

Additional context
Resource handler returned message: "Access denied for operation 'AWS::CloudFront::Distribution: You don't have permission to access the S3 bucket for CloudFront logs: tlv-video-on-demand2-logs6819bb44-hi0kc3kp3sgr.s3.il-central-1.amazonaws.com If you're using IAM, you need s3:GetBucketAcl and s3:PutBucketAcl permissions to create a distribution or to update log settings for an existing distribution. In addition, the S3 ACL for the bucket must grant you FULL_CONTROL. (Service: CloudFront, Status Code: 403, Request ID: 9055e875-32a7-47b2-8bb6-3c2755592765)'." (RequestToken: 6edcdc85-1361-d6a9-8dd3-6fd77c8752a4, HandlerErrorCode: AccessDenied)

![Screenshot 2023-12-24 at 13 56 49](https://github.com/aws-solutions/video-on-demand-on-aws-foundation/assets/68636084/40a5d87a-7f4b-4049-9e0c-71b124434f29)

**Comment by raulmlamzn** [comment]
Thank you for your suggestion @veltz-avi. We will consider your feedback to support the solution in the "il-central-1" region in the future, however AWS Elemental MediaConvert is currently not supported in the region. 
You can check the list of AWS Services Available by Region here: https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/?p=ngi&loc=4
